---
image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKERIMG: brokenpip3/my-pkgbuild

services:
  - docker:dind

stages:
  # Build and push docker img
  - build
  # Pkgbuild
  - pkgbuild

build_image:
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$DOCKERIMG .
    - docker push $CI_REGISTRY/$DOCKERIMG

lxd:
  stage: pkgbuild
  image: $CI_REGISTRY/$DOCKERIMG
  allow_failure: true
  script:
    - ./check_version.sh lxd
    - ./build.sh lxd
  
lxd-forward-git:  
  stage: pkgbuild
  image: $CI_REGISTRY/$DOCKERIMG
  allow_failure: true
  script:
    - ./build.sh lxd-forward-git True
...
